title: QMUL Reinforcement Learning
url: "https://qmul-rl.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

author_name: "QMUL Reinforcement Learning" # change this to your name

footer: yes
#footer_url: "https://github.com/ankitsultana"
footer_text: "QMUL RL"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "People"
   link: "people"
 - name: "Contact"
   link: "contact"
