title: QMUL Reinforcement Learning
url: "https://qmul-rl.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: "https://github.com/ankitsultana"
footer_text: "QMUL Reinforcement Learning"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
